version: '3'

services:
  nodeserver:
    image: nodeserver
    container_name: tickets
    build:
      context: .
      dockerfile: .
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - 9229:9229
      - ${SERVER_PORT}:${SERVER_PORT}
    expose:
      - ${SERVER_PORT}
      - 9229
    volumes:
      - .:/var/www/tickets
    networks:
      - ticket_project

  db:
    container_name: ticket_db
    image: postgres:13
    env_file:
      - .env
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ticket_db:/var/lib/postgresql/data
    networks:
      - ticket_project


volumes:
  ticket_db:


networks:
  ticket_project:
    driver: bridge
